### ISSUE TITLE
Updating @types/vscode to 1.44 breaks vscode-languageclient

### ISSUE THREAD

**Issue by kjeremy** [microsoft/vscode-languageserver-node#610]
After upgrading our extension's @types/vscode to 1.44 (vscode-languageclient is at 6.1.3) I am see a lot of errors like the following:

> node_modules/@types/vscode/index.d.ts:3168:15 - error TS2300: Duplicate identifier 'SemanticTokensLegend'.
> 
> 3168  export class SemanticTokensLegend {
>                    ~~~~~~~~~~~~~~~~~~~~
> 
>   node_modules/vscode-languageclient/lib/semanticTokens.proposed.d.ts:5:11
>     5     class SemanticTokensLegend {
>                 ~~~~~~~~~~~~~~~~~~~~
>     'SemanticTokensLegend' was also declared here.
> 
> node_modules/@types/vscode/index.d.ts:3185:15 - error TS2300: Duplicate identifier 'SemanticTokensBuilder'.
> 
> 3185  export class SemanticTokensBuilder {
>                    ~~~~~~~~~~~~~~~~~~~~~
> 
>   node_modules/vscode-languageclient/lib/semanticTokens.proposed.d.ts:10:11
>     10     class SemanticTokensBuilder {
>                  ~~~~~~~~~~~~~~~~~~~~~
>     'SemanticTokensBuilder' was also declared here.
> 
> node_modules/@types/vscode/index.d.ts:3220:15 - error TS2300: Duplicate identifier 'SemanticTokens'.
> 
> 3220  export class SemanticTokens {
>                    ~~~~~~~~~~~~~~
> 
>   node_modules/vscode-languageclient/lib/semanticTokens.proposed.d.ts:15:11
>     15     class SemanticTokens {
>                  ~~~~~~~~~~~~~~
>     'SemanticTokens' was also declared here.
> 
> node_modules/@types/vscode/index.d.ts:3240:15 - error TS2300: Duplicate identifier 'SemanticTokensEdits'.
> 
> 3240  export class SemanticTokensEdits {
>                    ~~~~~~~~~~~~~~~~~~~
> 
>   node_modules/vscode-languageclient/lib/semanticTokens.proposed.d.ts:25:11
>     25     class SemanticTokensEdits {
>                  ~~~~~~~~~~~~~~~~~~~
>     'SemanticTokensEdits' was also declared here.
> 
> node_modules/@types/vscode/index.d.ts:3260:15 - error TS2300: Duplicate identifier 'SemanticTokensEdit'.
> 
> 3260  export class SemanticTokensEdit {
>                    ~~~~~~~~~~~~~~~~~~
> 
>   node_modules/vscode-languageclient/lib/semanticTokens.proposed.d.ts:35:11
>     35     class SemanticTokensEdit {
>                  ~~~~~~~~~~~~~~~~~~
>     'SemanticTokensEdit' was also declared here.
> 
> node_modules/vscode-languageclient/lib/semanticTokens.proposed.d.ts:5:11 - error TS2300: Duplicate identifier 'SemanticTokensLegend'.

**Comment by kjeremy** [comment]
Also happens with vscode-languageclient 6.2.0-next.2

**Comment by dbaeumer** [comment]
The reason for that is the change of the proposed API in VS Code itself. All I can do is to release new versions of the library.

**Comment by kjeremy** [comment]
To clarify: are you saying that you can fix the conflict by releasing a new version of the library or that this is out of your hands and all you can do is release a new version (which would not fix the problem)?

**Comment by dbaeumer** [comment]
No, I can release a new version which I just did. Client & Server at 7.0.0-next.1

**Comment by dbaeumer** [comment]
Fixing this on 6.1.x is not possible since moving to 1.44 API drags in quite some other stuff.
