### ISSUE TITLE
Implicit dependency in vscode-languageclient

### ISSUE THREAD

**Issue by reergymerej** [microsoft/vscode-languageserver-node#542]
I am trying to develop a client separate from the extension that uses it.  When trying, I am getting an error about missing `vscode`.

```
Error: Cannot find module 'vscode'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/Users/jeremygreer/Desktop/delete-me/node_modules/vscode-languageclient/lib/client.js:10:18)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
```

Here's [a minimal example](https://github.com/reergymerej/miss-clavel) of requiring `vscode-languageclient`.  Is there any way to get this to work?  Is there a missing dependency or is this error a red herring?

FWIW, `vscode-languageserver` works independently.  #505 is similar, but relates only to the server.

**Comment by SantanderAuhAuh** [comment]
Hi, man, have you already solve this problem? I just met the same.It will be so generous if you tell me the answer.Thank you.

**Comment by reergymerej** [comment]
It looks like it needs vcsode as a runtime. I wrote up an article with a very basic example  here. https://www.toptal.com/javascript/language-server-protocol-tutorial
Let me know if it helps.

**Comment by SantanderAuhAuh** [comment]
Thank you very much. But I have found an issue which is more simple. Anyway, thank you very much. https://stackoverflow.com/questions/56589711/strange-unresolved-dependencies-to-vscode-when-wrapping-monaco-editor-and-mona/56644955#56644955

**Comment by dbaeumer** [comment]
The `vscode-languageclient` depends on the VS Code API and doesn't work without it. It is simply the glue code to wire LSP to VS Code API.

If you need a client in NodeJS to talk to a server you can use `vscode-languageserver-protocol`. This has a simple connection to send notifications and request to a server and has no dependency on VS Code code.
