### ISSUE TITLE
node_modules/vscode-languageclient/lib/client.d.ts:413:33 - error TS2314: Generic type 'RequestType0<R, E>' requires 2 type argument(s).

### ISSUE THREAD

**Issue by brodao** [microsoft/vscode-languageserver-node#712]
Gentlemen,

I cannot determine the reason for the error mentioned in the title. I believe it is my environment, because on other machines the compilation of the occurrence without problems.
Can you help me?

My repository: https://github.com/brodao/tds-vscode
To reproduce: clone repository, open folder in VSCode, in terminal run "npm i" and after "npm run compile"

I think the problem happened when I migrated to TS 4.1 and removes the node_modules folder.

Grateful for the attention.

**Parcial log**

```
PS P:\github\tds-vscode> npm run compile

> tds-vscode@1.2.1 compile P:\github\tds-vscode
> npm-run-all compile:*


> tds-vscode@1.2.1 compile:extension P:\github\tds-vscode
> tsc -p ./src

node_modules/vscode-languageclient/lib/client.d.ts:2:19 - error TS2305: Module '"../../vscode-languageserver-protocol/lib/common/api"' has no exported member 'RPCMessageType'.

2 import { Message, RPCMessageType, ResponseError, RequestType, RequestType0, RequestHandler, RequestHandler0, GenericRequestHandler, NotificationType, NotificationType0, NotificationHandler, NotificationHandler0, GenericNotificationHandler, MessageReader, MessageWriter, Trace, Event, ClientCapabilities, TextDocumentRegistrationOptions, InitializeParams, InitializeResult, InitializeError, ServerCapabilities, DocumentSelector, DidOpenTextDocumentNotification, DidChangeTextDocumentNotification, DidCloseTextDocumentNotification, DidSaveTextDocumentNotification, WillSaveTextDocumentNotification, WillSaveTextDocumentWaitUntilRequest, FileEvent, CompletionRequest, HoverRequest, SignatureHelpRequest, DefinitionRequest, ReferencesRequest, DocumentHighlightRequest, WorkspaceSymbolRequest, CodeActionRequest, DocumentFormattingRequest, DocumentRangeFormattingRequest, DocumentOnTypeFormattingRequest, RenameRequest, DocumentLinkRequest, ProgressType, StaticRegistrationOptions, DocumentColorRequest, DeclarationRequest, FoldingRangeRequest, ImplementationRequest, SelectionRangeRequest, TypeDefinitionRequest, Proposed } from 'vscode-languageserver-protocol';
                    ~~~~~~~~~~~~~~

node_modules/vscode-languageclient/lib/client.d.ts:413:33 - error TS2314: Generic type 'RequestType0<R, E>' requires 2 type argument(s).

413     sendRequest<R, E, RO>(type: RequestType0<R, E, RO>, token?: CancellationToken): Promise<R>;
                                    ~~~~~~~~~~~~~~~~~~~~~~

node_modules/vscode-languageclient/lib/client.d.ts:414:36 - error TS2314: Generic type 'RequestType<P, R, E>' requires 3 type argument(s).   

414     sendRequest<P, R, E, RO>(type: RequestType<P, R, E, RO>, params: P, token?: CancellationToken): Promise<R>;
                                       ~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/vscode-languageclient/lib/client.d.ts:417:31 - error TS2314: Generic type 'RequestType0<R, E>' requires 2 type argument(s).

417     onRequest<R, E, RO>(type: RequestType0<R, E, RO>, handler: RequestHandler0<R, E>): void;
                                  ~~~~~~~~~~~~~~~~~~~~~~
```

PS: Sorry my bad english.

**Comment by hmmmmniek** [comment]
This is caused by #710

**Comment by brodao** [comment]
@hmmmmniek ,
> This is caused by #710
Thanks. Your solution also worked for me.
