### ISSUE TITLE
Code that compiled with 4.3.0 on Mac fails to compile on 4.4.0

### ISSUE THREAD

**Issue by StephenWeatherford** [Microsoft/vscode-languageserver-node#378]
NOTE: This does not repro on Windows

You can see this in the following repo:
1) git clone https://github.com/Microsoft/vscode-cosmosdb
2) cd vscode-cosmosdb
3) npm i
4) npm build

> vscode-cosmosdb@0.8.1-alpha build /Users/stephwe/repos/vscode-cosmosdb
> tsc -p ./

node_modules/vscode-languageclient/lib/client.d.ts:1:707 - error TS2305: Module ''vscode'' has no exported member 'DocumentSymbol'.

1 import { TextDocumentChangeEvent, TextDocument, Disposable, OutputChannel, FileSystemWatcher as VFileSystemWatcher, DiagnosticCollection, Diagnostic as VDiagnostic, Uri, ProviderResult, CancellationToken, Position as VPosition, Location as VLocation, Range as VRange, CompletionItem as VCompletionItem, CompletionList as VCompletionList, SignatureHelp as VSignatureHelp, Definition as VDefinition, DocumentHighlight as VDocumentHighlight, SymbolInformation as VSymbolInformation, CodeActionContext as VCodeActionContext, Command as VCommand, CodeLens as VCodeLens, FormattingOptions as VFormattingOptions, TextEdit as VTextEdit, WorkspaceEdit as VWorkspaceEdit, Hover as VHover, CodeAction as VCodeAction, DocumentSymbol as VDocumentSymbol, DocumentLink as VDocumentLink, TextDocumentWillSaveEvent, WorkspaceFolder as VWorkspaceFolder, CompletionContext as VCompletionContext } from 'vscode';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ~~~~~~~~~~~~~~


node_modules/vscode-languageclient/lib/protocolConverter.d.ts:54:54 - error TS2694: Namespace ''vscode'' has no exported member 'DocumentSymbol'.

54     asDocumentSymbol(value: ls.DocumentSymbol): code.DocumentSymbol;
                                                        ~~~~~~~~~~~~~~


node_modules/vscode-languageclient/lib/protocolConverter.d.ts:56:57 - error TS2694: Namespace ''vscode'' has no exported member 'DocumentSymbol'.

56     asDocumentSymbols(value: ls.DocumentSymbol[]): code.DocumentSymbol[];
                                                           ~~~~~~~~~~~~~~


node_modules/vscode-languageclient/lib/protocolConverter.d.ts:57:76 - error TS2694: Namespace ''vscode'' has no exported member 'DocumentSymbol'.

57     asDocumentSymbols(value: ls.DocumentSymbol[] | undefined | null): code.DocumentSymbol[] | undefined;
                                                                              ~~~~~~~~~~~~~~

**Comment by StephenWeatherford** [comment]
That works, thanks, although I have no idea how we're supposed to know this is necessary.
