### ISSUE TITLE
LinkedEditingRanges reported as duplicate identifier

### ISSUE THREAD

**Issue by Razzeee** [microsoft/vscode-languageserver-node#707]
Hey there, I'm importing these two, as we've always done:

```
 "dependencies": {
    "vscode-languageclient": "^7.0.0-next.16"
  },
  "devDependencies": {
    "@types/vscode": "^1.52.0"
   }
```

But they seem to collide now:
```
Error: node_modules/@types/vscode/index.d.ts(4558,18): error TS2300: Duplicate identifier 'LinkedEditingRanges'.
Error: node_modules/vscode-languageclient/typings/vscode-proposed.d.ts(7,15): error TS2300: Duplicate identifier 'LinkedEditingRanges'.
```
https://github.com/elm-tooling/elm-language-client-vscode/runs/1542587892?check_suite_focus=true

Looking at https://github.com/microsoft/vscode-languageserver-node/commit/31664dc752b74c3c00c0422c7c6e025f985bf549 you seem to be doing something similar, but don't run into that error?

**Comment by dbaeumer** [comment]
The problem is that the next version only works with 1.51 since the API has moved to final. I will publish a new version for 1.52 today,
