### ISSUE TITLE
vscode-jsonrpc types

### ISSUE THREAD

**Issue by char0n** [microsoft/vscode-languageserver-node#1590]
Hi, 

It seems that the `vscode-jsonrpc` typings don't work with TypeScript higher than `5.5.4`. Would it be possible to update the TypScript in this repo to latest version (v5.7.2), compesate with typings and release a new version?

Thank you very much for all the work!

```
../../node_modules/vscode-jsonrpc/lib/common/linkedMap.d.ts:28:5 - error TS2416: Property 'forEach' in type 'LinkedMap<K, V>' is not assignable to the same property in base type 'Map<K, V>'.
  Type '(callbackfn: (value: V, key: K, map: LinkedMap<K, V>) => void, thisArg?: any) => void' is not assignable to type '(callbackfn: (value: V, key: K, map: Map<K, V>) => void, thisArg?: any) => void'.
    Types of parameters 'callbackfn' and 'callbackfn' are incompatible.
      Types of parameters 'map' and 'map' are incompatible.
        Type 'LinkedMap<K, V>' is not assignable to type 'Map<K, V>'.
          The types returned by 'entries()' are incompatible between these types.
            Type 'IterableIterator<[K, V]>' is missing the following properties from type 'MapIterator<[K, V]>': map, filter, take, drop, and 9 more.

28     forEach(callbackfn: (value: V, key: K, map: LinkedMap<K, V>) => void, thisArg?: any): void;
       ~~~~~~~

../../node_modules/vscode-jsonrpc/lib/common/linkedMap.d.ts:29:5 - error TS2416: Property 'keys' in type 'LinkedMap<K, V>' is not assignable to the same property in base type 'Map<K, V>'.
  Type '() => IterableIterator<K>' is not assignable to type '() => MapIterator<K>'.
    Type 'IterableIterator<K>' is missing the following properties from type 'MapIterator<K>': map, filter, take, drop, and 9 more.

29     keys(): IterableIterator<K>;
       ~~~~

../../node_modules/vscode-jsonrpc/lib/common/linkedMap.d.ts:30:5 - error TS2416: Property 'values' in type 'LinkedMap<K, V>' is not assignable to the same property in base type 'Map<K, V>'.
  Type '() => IterableIterator<V>' is not assignable to type '() => MapIterator<V>'.
    Type 'IterableIterator<V>' is missing the following properties from type 'MapIterator<V>': map, filter, take, drop, and 9 more.

30     values(): IterableIterator<V>;
       ~~~~~~

../../node_modules/vscode-jsonrpc/lib/common/linkedMap.d.ts:31:5 - error TS2416: Property 'entries' in type 'LinkedMap<K, V>' is not assignable to the same property in base type 'Map<K, V>'.
  Type '() => IterableIterator<[K, V]>' is not assignable to type '() => MapIterator<[K, V]>'.
    Type 'IterableIterator<[K, V]>' is missing the following properties from type 'MapIterator<[K, V]>': map, filter, take, drop, and 9 more.

31     entries(): IterableIterator<[K, V]>;
       ~~~~~~~

../../node_modules/vscode-jsonrpc/lib/common/linkedMap.d.ts:32:5 - error TS2416: Property '[Symbol.iterator]' in type 'LinkedMap<K, V>' is not assignable to the same property in base type 'Map<K, V>'.
  Type '() => IterableIterator<[K, V]>' is not assignable to type '() => MapIterator<[K, V]>'.
    Type 'IterableIterator<[K, V]>' is missing the following properties from type 'MapIterator<[K, V]>': map, filter, take, drop, and 9 more.

32     [Symbol.iterator](): IterableIterator<[K, V]>;

```

**Comment by dbaeumer** [comment]
Have you tried the latest next version `9.0.0-next.5`. If you use the client / server lib there are corresponding next versions as well.

**Comment by dbaeumer** [comment]
I updated all dependencies to latest. So with the next release we should be fine https://github.com/microsoft/vscode-languageserver-node/pull/1592

**Comment by char0n** [comment]
Hi @dbaeumer,

I'm using `vscode-jsonrpc` as transitive dependency of `vscode-languageserver-protocol`. `vscode-languageserver-protocol@3.17.5` (latest version) is using vscode-jsonrpc@8.2.0. There now way to override for downstream consumers apart from using yarn resolution of npm overrides.

**Comment by char0n** [comment]
> Hmm, `vscode-languageserver-protocol` comes with json-rpc and re-exports it. So there should be no reason for you to have your own version.

Yes, I don't have my own version. What I meant was that my direct depedency is `vscode-languageserver-protocol@3.17.5` and it comes with `vscode-jsonrpc@8.2.0`.  `vscode-jsonrpc@8.2.0` does not work with TypeScript > `5.5.4` - that's where my problems comes from. 

But given https://github.com/microsoft/vscode-languageserver-node/issues/1590#issuecomment-2538594211, this problem will auto-correct in next release.

**Comment by char0n** [comment]
Hi again,

On Typescript@5.6 and higher following errors are still being produced. 

Version: vscode-jsonrpc@9.0.0-next.7

```
../../node_modules/vscode-jsonrpc/lib/common/linkedMap.d.ts:30:5 - error TS2416: Property 'forEach' in type 'LinkedMap<K, V>' is not assignable to the same property in base type 'Map<K, V>'.
  Type '(callbackfn: (value: V, key: K, map: LinkedMap<K, V>) => void, thisArg?: any) => void' is not assignable to type '(callbackfn: (value: V, key: K, map: Map<K, V>) => void, thisArg?: any) => void'.
    Types of parameters 'callbackfn' and 'callbackfn' are incompatible.
      Types of parameters 'map' and 'map' are incompatible.
        Type 'LinkedMap<K, V>' is not assignable to type 'Map<K, V>'.
          The types returned by 'entries()' are incompatible between these types.
            Type 'IterableIterator<[K, V]>' is missing the following properties from type 'MapIterator<[K, V]>': map, filter, take, drop, and 9 more.

30     forEach(callbackfn: (value: V, key: K, map: LinkedMap<K, V>) => void, thisArg?: any): void;
       ~~~~~~~

../../node_modules/vscode-jsonrpc/lib/common/linkedMap.d.ts:31:5 - error TS2416: Property 'keys' in type 'LinkedMap<K, V>' is not assignable to the same property in base type 'Map<K, V>'.
  Type '() => IterableIterator<K>' is not assignable to type '() => MapIterator<K>'.
    Type 'IterableIterator<K>' is missing the following properties from type 'MapIterator<K>': map, filter, take, drop, and 9 more.

31     keys(): IterableIterator<K>;
       ~~~~

../../node_modules/vscode-jsonrpc/lib/common/linkedMap.d.ts:32:5 - error TS2416: Property 'values' in type 'LinkedMap<K, V>' is not assignable to the same property in base type 'Map<K, V>'.
  Type '() => IterableIterator<V>' is not assignable to type '() => MapIterator<V>'.
    Type 'IterableIterator<V>' is missing the following properties from type 'MapIterator<V>': map, filter, take, drop, and 9 more.

32     values(): IterableIterator<V>;
       ~~~~~~

../../node_modules/vscode-jsonrpc/lib/common/linkedMap.d.ts:33:5 - error TS2416: Property 'entries' in type 'LinkedMap<K, V>' is not assignable to the same property in base type 'Map<K, V>'.
  Type '() => IterableIterator<[K, V]>' is not assignable to type '() => MapIterator<[K, V]>'.
    Type 'IterableIterator<[K, V]>' is missing the following properties from type 'MapIterator<[K, V]>': map, filter, take, drop, and 9 more.

33     entries(): IterableIterator<[K, V]>;
       ~~~~~~~

../../node_modules/vscode-jsonrpc/lib/common/linkedMap.d.ts:34:5 - error TS2416: Property '[Symbol.iterator]' in type 'LinkedMap<K, V>' is not assignable to the same property in base type 'Map<K, V>'.
  Type '() => IterableIterator<[K, V]>' is not assignable to type '() => MapIterator<[K, V]>'.
    Type 'IterableIterator<[K, V]>' is missing the following properties from type 'MapIterator<[K, V]>': map, filter, take, drop, and 9 more.

34     [Symbol.iterator](): IterableIterator<[K, V]>;
       ~~~~~~~~~~~~~~~~~
```

**Comment by tamird** [comment]
@char0n I believe that was fixed in https://github.com/microsoft/vscode-languageserver-node/pull/1644.

**Comment by char0n** [comment]
@tamird cool, but we still don't have a new fixing release
